functionsDirectory = "/Users/atakanbattal/Desktop/Uygulamalar/Telefoncular QMS/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/atakanbattal/Desktop/Uygulamalar/Telefoncular QMS/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/atakanbattal/Desktop/Uygulamalar/Telefoncular QMS/netlify/functions"

[build.environment]
VITE_SUPABASE_URL = "https://ryvczrubujzlanvqiqlk.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5dmN6cnVidWp6bGFudnFpcWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNDY0NDksImV4cCI6MjA5MDcyMjQ0OX0.v1-_uY9ISae_8p4juXzGro4FhxdDwCVD8Hos6HwbrHQ"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npm run dev"
targetPort = 3003.0
port = 8888.0
autoLaunch = false

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]